#!/bin/bash

while read oldrev newrev refname; do
    if [[ "$refname" == refs/heads/pr/* ]]; then
        echo "Pushes 'pr/*' branches should be sent over nostr, not through the git server"
        exit 1
    fi
done

exit 0