services:
  ngit-relay:
    build:
      context: ./src
    ports:
      - "8081:8081"
    env_file:
      - .env
    volumes:
      - ./volumes/repos:/srv/repos
      - ./volumes/blossom:/srv/blossom
      - ./volumes/relay-db:/relay-db
    restart: unless-stopped
    environment:
      - NGINX_ENTRYPOINTS_WORKER_CONNECTIONS=2048 # Consider moving this to .env if not needed here
