version: "3.8"

services:
  certbot:
    image: certbot/certbot:latest
    restart: unless-stopped
    # All operator-specific values live in .env
    env_file:
      - .env                     # EMAIL, DOMAINS, CERT_DOMAIN
    volumes:
      - letsencrypt:/etc/letsencrypt
      - certbot-webroot:/var/www/certbot

    entrypoint: |
      sh -e -c '
        : "${EMAIL?EMAIL missing in .env}"
        : "${DOMAINS?DOMAINS missing in .env}"

        certbot certonly --webroot -w /var/www/certbot \
               --agree-tos --no-eff-email --email "$EMAIL" \
               --domains "$DOMAINS" || true

        while true; do
          certbot renew --quiet
          sleep 12h
        done
      '

volumes:
  letsencrypt:
  certbot-webroot: