services:
  nginx:  # Renamed for clarity
    build:
      context: ./src
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - ./volumes/repos:/srv/repos
      - ./volumes/blossom:/srv/blossom
      - ./volumes/khatru-data:/khatru-data
      - letsencrypt:/etc/letsencrypt:ro          # keys & certs (read-only)
      - certbot-webroot:/var/www/certbot:ro      # ACME challenge files
    restart: unless-stopped
    environment:
      - NGINX_ENTRYPOINTS_WORKER_CONNECTIONS=2048  # Consider moving this to .env if not needed here
volumes:
  letsencrypt:
  certbot-webroot:



  