services:
  # Reverse-proxy + automatic HTTPS
  ssl-proxy:
    image: traefik:3.0
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --certificatesresolvers.le.acme.storage=/acme.json
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
      - --log.level=INFO
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme.json:/acme.json
    networks: [sslnet]
    restart: unless-stopped

  ngit-relay:
    networks: [sslnet]
    labels:
      traefik.enable: "true"
      traefik.http.routers.ngit-relay.rule: Host(`${NGIT_DOMAIN}`)
      traefik.http.routers.ngit-relay.entrypoints: websecure
      traefik.http.routers.ngit-relay.tls.certresolver: le
      traefik.http.services.ngit-relay.loadbalancer.server.port: "${NGIT_INTERNAL_RELAY_PORT_FOR_SSL_PROXY}"
    ports: [] # keep the container private; Traefik will proxy it

networks:
  sslnet:
