services:
  certbot:
    image: certbot/certbot:latest
    restart: unless-stopped
    # All operator-specific values live in .env
    env_file:
      - .env                     # DOMAINS, CERT_DOMAIN
    volumes:
      - letsencrypt:/etc/letsencrypt
      - certbot-webroot:/var/www/certbot

    entrypoint: |
      sh -e -c '
        : "${DOMAINS?DOMAINS missing in .env}"

        certbot certonly --webroot -w /var/www/certbot \
               --agree-tos --non-interactive\
               --domains "$DOMAINS" && break || {
                 echo "Certbot failed, waiting for 10 minutes before retrying..."
                 sleep 600  # Sleep for 10 minutes (600 seconds)
               }
        while true; do
          certbot renew --quiet
          sleep 12h
        done
      '

volumes:
  letsencrypt:
  certbot-webroot: