services:
  git:
    build:
      context: ./src
    ports:
      - "8080:8081"
      # - "443:8443"
    env_file:
      - .env
    volumes:
      - ./volumes/repos:/srv/repos
      - ./volumes/blossom:/srv/blossom
      - ./volumes/khatru-data:/khatru-data
    restart: unless-stopped
    environment:
      - NGINX_ENTRYPOINTS_WORKER_CONNECTIONS=2048
