services:
  ngit-relay:
    build:
      context: ./src
    ports:
      - "8081:8081"
    env_file:
      - .env
    volumes:
      - ./volumes/repos:/srv/ngit-relay/repos
      - ./volumes/blossom:/srv/ngit-relay/blossom
      - ./volumes/relay-db:/srv/ngit-relay/relay-db
      - ./volumes/logs:/var/log/ngit-relay
    restart: unless-stopped
    environment:
      - NGINX_ENTRYPOINTS_WORKER_CONNECTIONS=2048 # Consider moving this to .env if not needed here
